version: '3.2'
services:
  paramiko-client-1.15.0:
    image: rub-nds/paramiko-client:1.15.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.15.0
    profiles: [client]
  paramiko-client-1.15.1:
    image: rub-nds/paramiko-client:1.15.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.15.1
    profiles: [client]
  paramiko-client-1.15.2:
    image: rub-nds/paramiko-client:1.15.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.15.2
    profiles: [client]
  paramiko-client-1.15.3:
    image: rub-nds/paramiko-client:1.15.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.15.3
    profiles: [client]
  paramiko-client-1.15.4:
    image: rub-nds/paramiko-client:1.15.4
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.15.4
    profiles: [client]
  paramiko-client-1.15.5:
    image: rub-nds/paramiko-client:1.15.5
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.15.5
    profiles: [client]
  paramiko-client-1.16.0:
    image: rub-nds/paramiko-client:1.16.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.16.0
    profiles: [client]
  paramiko-client-1.16.1:
    image: rub-nds/paramiko-client:1.16.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.16.1
    profiles: [client]
  paramiko-client-1.16.2:
    image: rub-nds/paramiko-client:1.16.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.16.2
    profiles: [client]
  paramiko-client-1.16.3:
    image: rub-nds/paramiko-client:1.16.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.16.3
    profiles: [client]
  paramiko-client-1.17.0:
    image: rub-nds/paramiko-client:1.17.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.17.0
    profiles: [client]
  paramiko-client-1.17.1:
    image: rub-nds/paramiko-client:1.17.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.17.1
    profiles: [client]
  paramiko-client-1.17.2:
    image: rub-nds/paramiko-client:1.17.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.17.2
    profiles: [client]
  paramiko-client-1.17.3:
    image: rub-nds/paramiko-client:1.17.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.17.3
    profiles: [client]
  paramiko-client-1.17.4:
    image: rub-nds/paramiko-client:1.17.4
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.17.4
    profiles: [client]
  paramiko-client-1.17.5:
    image: rub-nds/paramiko-client:1.17.5
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.17.5
    profiles: [client]
  paramiko-client-1.17.6:
    image: rub-nds/paramiko-client:1.17.6
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.17.6
    profiles: [client]
  paramiko-client-1.18.0:
    image: rub-nds/paramiko-client:1.18.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.18.0
    profiles: [client]
  paramiko-client-1.18.1:
    image: rub-nds/paramiko-client:1.18.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.18.1
    profiles: [client]
  paramiko-client-1.18.2:
    image: rub-nds/paramiko-client:1.18.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.18.2
    profiles: [client]
  paramiko-client-1.18.3:
    image: rub-nds/paramiko-client:1.18.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.18.3
    profiles: [client]
  paramiko-client-1.18.4:
    image: rub-nds/paramiko-client:1.18.4
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.18.4
    profiles: [client]
  paramiko-client-1.18.5:
    image: rub-nds/paramiko-client:1.18.5
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 1.18.5
    profiles: [client]
  paramiko-client-2.0.0:
    image: rub-nds/paramiko-client:2.0.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.0
    profiles: [client]
  paramiko-client-2.0.1:
    image: rub-nds/paramiko-client:2.0.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.1
    profiles: [client]
  paramiko-client-2.0.2:
    image: rub-nds/paramiko-client:2.0.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.2
    profiles: [client]
  paramiko-client-2.0.3:
    image: rub-nds/paramiko-client:2.0.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.3
    profiles: [client]
  paramiko-client-2.0.4:
    image: rub-nds/paramiko-client:2.0.4
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.4
    profiles: [client]
  paramiko-client-2.0.5:
    image: rub-nds/paramiko-client:2.0.5
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.5
    profiles: [client]
  paramiko-client-2.0.7:
    image: rub-nds/paramiko-client:2.0.7
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.7
    profiles: [client]
  paramiko-client-2.0.8:
    image: rub-nds/paramiko-client:2.0.8
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.8
    profiles: [client]
  paramiko-client-2.0.9:
    image: rub-nds/paramiko-client:2.0.9
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.9
    profiles: [client]
  paramiko-client-2.0.8:
    image: rub-nds/paramiko-client:2.0.8
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.0.8
    profiles: [client]
  paramiko-client-2.1.0:
    image: rub-nds/paramiko-client:2.1.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.1.0
    profiles: [client]
  paramiko-client-2.1.2:
    image: rub-nds/paramiko-client:2.1.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.1.2
    profiles: [client]
  paramiko-client-2.1.3:
    image: rub-nds/paramiko-client:2.1.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.1.3
    profiles: [client]
  paramiko-client-2.1.4:
    image: rub-nds/paramiko-client:2.1.4
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.1.4
    profiles: [client]
  paramiko-client-2.1.5:
    image: rub-nds/paramiko-client:2.1.5
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.1.5
    profiles: [client]
  paramiko-client-2.1.6:
    image: rub-nds/paramiko-client:2.1.6
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.1.6
    profiles: [client]
  paramiko-client-2.2.0:
    image: rub-nds/paramiko-client:2.2.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.2.0
    profiles: [client]
  paramiko-client-2.2.1:
    image: rub-nds/paramiko-client:2.2.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.2.1
    profiles: [client]
  paramiko-client-2.2.2:
    image: rub-nds/paramiko-client:2.2.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.2.2
    profiles: [client]
  paramiko-client-2.2.3:
    image: rub-nds/paramiko-client:2.2.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.2.3
    profiles: [client]
  paramiko-client-2.2.4:
    image: rub-nds/paramiko-client:2.2.4
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.2.4
    profiles: [client]
  paramiko-client-2.3.0:
    image: rub-nds/paramiko-client:2.3.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.3.0
    profiles: [client]
  paramiko-client-2.3.1:
    image: rub-nds/paramiko-client:2.3.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.3.1
    profiles: [client]
  paramiko-client-2.3.2:
    image: rub-nds/paramiko-client:2.3.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.3.2
    profiles: [client]
  paramiko-client-2.3.3:
    image: rub-nds/paramiko-client:2.3.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.3.3
    profiles: [client]
  paramiko-client-2.4.0:
    image: rub-nds/paramiko-client:2.4.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.4.0
    profiles: [client]
  paramiko-client-2.4.1:
    image: rub-nds/paramiko-client:2.4.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.4.1
    profiles: [client]
  paramiko-client-2.4.3:
    image: rub-nds/paramiko-client:2.4.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.4.3
    profiles: [client]
  paramiko-client-2.4.2:
    image: rub-nds/paramiko-client:2.4.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.4.2
    profiles: [client]
  paramiko-client-2.5.0:
    image: rub-nds/paramiko-client:2.5.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.5.0
    profiles: [client]
  paramiko-client-2.5.1:
    image: rub-nds/paramiko-client:2.5.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.5.1
    profiles: [client]
  paramiko-client-2.6.0:
    image: rub-nds/paramiko-client:2.6.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.6.0
    profiles: [client]
  paramiko-client-2.7.0:
    image: rub-nds/paramiko-client:2.7.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.7.0
    profiles: [client]
  paramiko-client-2.7.1:
    image: rub-nds/paramiko-client:2.7.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.7.1
    profiles: [client]
  paramiko-client-2.7.2:
    image: rub-nds/paramiko-client:2.7.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.7.2
    profiles: [client]
  paramiko-client-2.8.0:
    image: rub-nds/paramiko-client:2.8.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.8.0
    profiles: [client]
  paramiko-client-2.8.1:
    image: rub-nds/paramiko-client:2.8.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.8.1
    profiles: [client]
  paramiko-client-2.9.0:
    image: rub-nds/paramiko-client:2.9.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.9.0
    profiles: [client]
  paramiko-client-2.9.1:
    image: rub-nds/paramiko-client:2.9.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.9.1
    profiles: [client]
  paramiko-client-2.9.2:
    image: rub-nds/paramiko-client:2.9.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.9.2
    profiles: [client]
  paramiko-client-2.9.3:
    image: rub-nds/paramiko-client:2.9.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.9.3
    profiles: [client]
  paramiko-client-2.9.4:
    image: rub-nds/paramiko-client:2.9.4
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.9.4
    profiles: [client]
  paramiko-client-2.9.5:
    image: rub-nds/paramiko-client:2.9.5
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.9.5
    profiles: [client]
  paramiko-client-2.10.0:
    image: rub-nds/paramiko-client:2.10.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.10.0
    profiles: [client]
  paramiko-client-2.10.1:
    image: rub-nds/paramiko-client:2.10.1
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.10.1
    profiles: [client]
  paramiko-client-2.10.2:
    image: rub-nds/paramiko-client:2.10.2
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.10.2
    profiles: [client]
  paramiko-client-2.10.3:
    image: rub-nds/paramiko-client:2.10.3
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.10.3
    profiles: [client]
  paramiko-client-2.10.4:
    image: rub-nds/paramiko-client:2.10.4
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.10.4
    profiles: [client]
  paramiko-client-2.10.5:
    image: rub-nds/paramiko-client:2.10.5
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.10.5
    profiles: [client]
  paramiko-client-2.11.0:
    image: rub-nds/paramiko-client:2.11.0
    build:
      context: .
      target: paramiko-client
      args:
        VERSION: 2.11.0
    profiles: [client]
