version: '3.2'
services:
  openssh-client-7.0p1:
    image: rub-nds/openssh-client:7.0p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.0p1
    profiles: [ client ]
  openssh-client-7.1p1:
    image: rub-nds/openssh-client:7.1p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.1p1
    profiles: [ client ]
  openssh-client-7.2p1:
    image: rub-nds/openssh-client:7.2p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.2p1
    profiles: [ client ]
  openssh-client-7.2p2:
    image: rub-nds/openssh-client:7.2p2
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.2p2
    profiles: [ client ]
  openssh-client-7.3p1:
    image: rub-nds/openssh-client:7.3p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.3p1
    profiles: [ client ]
  openssh-client-7.4p1:
    image: rub-nds/openssh-client:7.4p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.4p1
    profiles: [ client ]
  openssh-client-7.5p1:
    image: rub-nds/openssh-client:7.5p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.5p1
    profiles: [ client ]
  openssh-client-7.6p1:
    image: rub-nds/openssh-client:7.6p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.6p1
    profiles: [ client ]
  openssh-client-7.7p1:
    image: rub-nds/openssh-client:7.7p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 7.7p1
    profiles: [ client ]
  openssh-client-8.4p1:
    image: rub-nds/openssh-client:8.4p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 8.4p1
    profiles: [ client ]
  openssh-client-8.5p1:
    image: rub-nds/openssh-client:8.5p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 8.5p1
    profiles: [ client ]
  openssh-client-8.6p1:
    image: rub-nds/openssh-client:8.6p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 8.6p1
    profiles: [ client ]
  openssh-client-8.7p1:
    image: rub-nds/openssh-client:8.7p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 8.7p1
    profiles: [ client ]
  openssh-client-8.8p1:
    image: rub-nds/openssh-client:8.8p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 8.8p1
    profiles: [ client ]
  openssh-client-9.0p1:
    image: rub-nds/openssh-client:9.0p1
    build:
      context: .
      dockerfile: Dockerfile
      target: openssh-client
      args:
        VERSION: 9.0p1
    profiles: [ client ]
  openssh-client-8.0p1:
    image: rub-nds/openssh-client:8.0p1
    build:
      context: .
      dockerfile: Dockerfile2
      target: openssh-client
      args:
        VERSION: 8.0p1
    profiles: [ client ]
  openssh-client-8.1p1:
    image: rub-nds/openssh-client:8.1p1
    build:
      context: .
      dockerfile: Dockerfile2
      target: openssh-client
      args:
        VERSION: 8.1p1
    profiles: [ client ]
  openssh-client-8.2p1:
    image: rub-nds/openssh-client:8.2p1
    build:
      context: .
      dockerfile: Dockerfile2
      target: openssh-client
      args:
        VERSION: 8.2p1
    profiles: [ client ]
  openssh-client-8.3p1:
    image: rub-nds/openssh-client:8.3p1
    build:
      context: .
      dockerfile: Dockerfile2
      target: openssh-client
      args:
        VERSION: 8.3p1
    profiles: [ client ]
  openssh-client-7.8p1:
    image: rub-nds/openssh-client:7.8p1
    build:
      context: .
      dockerfile: Dockerfile3
      target: openssh-client
      args:
        VERSION: 7.8p1
    profiles: [ client ]
  openssh-client-7.9p1:
    image: rub-nds/openssh-client:7.9p1
    build:
      context: .
      dockerfile: Dockerfile3
      target: openssh-client
      args:
        VERSION: 7.9p1
    profiles: [ client ]
