services:
  bitvise-server-8.15:
    image: rub-nds/bitvise-server:8.15
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.15
  bitvise-server-8.16:
    image: rub-nds/bitvise-server:8.16
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.16
  bitvise-server-8.17:
    image: rub-nds/bitvise-server:8.17
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.17
  bitvise-server-8.18:
    image: rub-nds/bitvise-server:8.18
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.18
  bitvise-server-8.19:
    image: rub-nds/bitvise-server:8.19
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.19
  bitvise-server-8.21:
    image: rub-nds/bitvise-server:8.21
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.21
  bitvise-server-8.22:
    image: rub-nds/bitvise-server:8.22
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.22
  bitvise-server-8.24:
    image: rub-nds/bitvise-server:8.24
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.24
  bitvise-server-8.25:
    image: rub-nds/bitvise-server:8.25
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.25
  bitvise-server-8.26:
    image: rub-nds/bitvise-server:8.26
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.26
  bitvise-server-8.27:
    image: rub-nds/bitvise-server:8.27
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.27
  bitvise-server-8.28:
    image: rub-nds/bitvise-server:8.28
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.28
  bitvise-server-8.29:
    image: rub-nds/bitvise-server:8.29
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.29
  bitvise-server-8.31:
    image: rub-nds/bitvise-server:8.31
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.31
  bitvise-server-8.32:
    image: rub-nds/bitvise-server:8.32
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.32
  bitvise-server-8.33:
    image: rub-nds/bitvise-server:8.33
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.33
  bitvise-server-8.34:
    image: rub-nds/bitvise-server:8.34
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.34
  bitvise-server-8.35:
    image: rub-nds/bitvise-server:8.35
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.35
  bitvise-server-8.36:
    image: rub-nds/bitvise-server:8.36
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.36
  bitvise-server-8.37:
    image: rub-nds/bitvise-server:8.37
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.37
  bitvise-server-8.38:
    image: rub-nds/bitvise-server:8.38
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.38
  bitvise-server-8.39:
    image: rub-nds/bitvise-server:8.39
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.39
  bitvise-server-8.41:
    image: rub-nds/bitvise-server:8.41
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.41
  bitvise-server-8.42:
    image: rub-nds/bitvise-server:8.42
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.42
  bitvise-server-8.43:
    image: rub-nds/bitvise-server:8.43
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.43
  bitvise-server-8.44:
    image: rub-nds/bitvise-server:8.44
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.44
  bitvise-server-8.45:
    image: rub-nds/bitvise-server:8.45
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.45
  bitvise-server-8.47:
    image: rub-nds/bitvise-server:8.47
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.47
  bitvise-server-8.48:
    image: rub-nds/bitvise-server:8.48
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.48
  bitvise-server-8.49:
    image: rub-nds/bitvise-server:8.49
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 8.49
  bitvise-server-9.12:
    image: rub-nds/bitvise-server:9.12
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.12
  bitvise-server-9.14:
    image: rub-nds/bitvise-server:9.14
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.14
  bitvise-server-9.16:
    image: rub-nds/bitvise-server:9.16
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.16
  bitvise-server-9.17:
    image: rub-nds/bitvise-server:9.17
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.17
  bitvise-server-9.18:
    image: rub-nds/bitvise-server:9.18
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.18
  bitvise-server-9.19:
    image: rub-nds/bitvise-server:9.19
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.19
  bitvise-server-9.21:
    image: rub-nds/bitvise-server:9.21
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.21
  bitvise-server-9.22:
    image: rub-nds/bitvise-server:9.22
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.22
  bitvise-server-9.23:
    image: rub-nds/bitvise-server:9.23
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.23
  bitvise-server-9.24:
    image: rub-nds/bitvise-server:9.24
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.24
  bitvise-server-9.25:
    image: rub-nds/bitvise-server:9.25
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.25
  bitvise-server-9.26:
    image: rub-nds/bitvise-server:9.26
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.26
  bitvise-server-9.27:
    image: rub-nds/bitvise-server:9.27
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.27
  bitvise-server-9.28:
    image: rub-nds/bitvise-server:9.28
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.28
  bitvise-server-9.31:
    image: rub-nds/bitvise-server:9.31
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.31
  bitvise-server-9.33:
    image: rub-nds/bitvise-server:9.33
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.33
  bitvise-server-9.34:
    image: rub-nds/bitvise-server:9.34
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.34
  bitvise-server-9.35:
    image: rub-nds/bitvise-server:9.35
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.35
  bitvise-server-9.37:
    image: rub-nds/bitvise-server:9.37
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.37
  bitvise-server-9.38:
    image: rub-nds/bitvise-server:9.38
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.38
  bitvise-server-9.39:
    image: rub-nds/bitvise-server:9.39
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.39
  bitvise-server-9.41:
    image: rub-nds/bitvise-server:9.41
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.41
  bitvise-server-9.42:
    image: rub-nds/bitvise-server:9.42
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.42
  bitvise-server-9.43:
    image: rub-nds/bitvise-server:9.43
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        VERSION: 9.43
  bitvise-client-8.15:
    image: rub-nds/bitvise-client:8.15
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.15
    profiles: [client]
  bitvise-client-8.16:
    image: rub-nds/bitvise-client:8.16
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.16
    profiles: [client]
  bitvise-client-8.17:
    image: rub-nds/bitvise-client:8.17
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.17
    profiles: [client]
  bitvise-client-8.18:
    image: rub-nds/bitvise-client:8.18
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.18
    profiles: [client]
  bitvise-client-8.19:
    image: rub-nds/bitvise-client:8.19
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.19
    profiles: [client]
  bitvise-client-8.21:
    image: rub-nds/bitvise-client:8.21
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.21
    profiles: [client]
  bitvise-client-8.22:
    image: rub-nds/bitvise-client:8.22
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.22
    profiles: [client]
  bitvise-client-8.24:
    image: rub-nds/bitvise-client:8.24
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.24
    profiles: [client]
  bitvise-client-8.25:
    image: rub-nds/bitvise-client:8.25
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.25
    profiles: [client]
  bitvise-client-8.26:
    image: rub-nds/bitvise-client:8.26
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.26
    profiles: [client]
  bitvise-client-8.27:
    image: rub-nds/bitvise-client:8.27
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.27
    profiles: [client]
  bitvise-client-8.28:
    image: rub-nds/bitvise-client:8.28
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.28
    profiles: [client]
  bitvise-client-8.29:
    image: rub-nds/bitvise-client:8.29
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.29
    profiles: [client]
  bitvise-client-8.31:
    image: rub-nds/bitvise-client:8.31
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.31
    profiles: [client]
  bitvise-client-8.32:
    image: rub-nds/bitvise-client:8.32
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.32
    profiles: [client]
  bitvise-client-8.33:
    image: rub-nds/bitvise-client:8.33
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.33
    profiles: [client]
  bitvise-client-8.34:
    image: rub-nds/bitvise-client:8.34
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.34
    profiles: [client]
  bitvise-client-8.35:
    image: rub-nds/bitvise-client:8.35
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.35
    profiles: [client]
  bitvise-client-8.36:
    image: rub-nds/bitvise-client:8.36
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.36
    profiles: [client]
  bitvise-client-8.37:
    image: rub-nds/bitvise-client:8.37
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.37
    profiles: [client]
  bitvise-client-8.38:
    image: rub-nds/bitvise-client:8.38
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.38
    profiles: [client]
  bitvise-client-8.39:
    image: rub-nds/bitvise-client:8.39
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.39
    profiles: [client]
  bitvise-client-8.41:
    image: rub-nds/bitvise-client:8.41
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.41
    profiles: [client]
  bitvise-client-8.42:
    image: rub-nds/bitvise-client:8.42
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.42
    profiles: [client]
  bitvise-client-8.43:
    image: rub-nds/bitvise-client:8.43
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.43
    profiles: [client]
  bitvise-client-8.44:
    image: rub-nds/bitvise-client:8.44
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.44
    profiles: [client]
  bitvise-client-8.45:
    image: rub-nds/bitvise-client:8.45
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.45
    profiles: [client]
  bitvise-client-8.47:
    image: rub-nds/bitvise-client:8.47
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.47
    profiles: [client]
  bitvise-client-8.48:
    image: rub-nds/bitvise-client:8.48
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.48
    profiles: [client]
  bitvise-client-8.49:
    image: rub-nds/bitvise-client:8.49
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 8.49
    profiles: [client]
  bitvise-client-9.12:
    image: rub-nds/bitvise-client:9.12
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.12
    profiles: [client]
  bitvise-client-9.14:
    image: rub-nds/bitvise-client:9.14
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.14
    profiles: [client]
  bitvise-client-9.16:
    image: rub-nds/bitvise-client:9.16
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.16
    profiles: [client]
  bitvise-client-9.17:
    image: rub-nds/bitvise-client:9.17
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.17
    profiles: [client]
  bitvise-client-9.18:
    image: rub-nds/bitvise-client:9.18
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.18
    profiles: [client]
  bitvise-client-9.19:
    image: rub-nds/bitvise-client:9.19
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.19
    profiles: [client]
  bitvise-client-9.21:
    image: rub-nds/bitvise-client:9.21
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.21
    profiles: [client]
  bitvise-client-9.22:
    image: rub-nds/bitvise-client:9.22
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.22
    profiles: [client]
  bitvise-client-9.23:
    image: rub-nds/bitvise-client:9.23
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.23
    profiles: [client]
  bitvise-client-9.24:
    image: rub-nds/bitvise-client:9.24
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.24
    profiles: [client]
  bitvise-client-9.25:
    image: rub-nds/bitvise-client:9.25
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.25
    profiles: [client]
  bitvise-client-9.26:
    image: rub-nds/bitvise-client:9.26
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.26
    profiles: [client]
  bitvise-client-9.27:
    image: rub-nds/bitvise-client:9.27
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.27
    profiles: [client]
  bitvise-client-9.28:
    image: rub-nds/bitvise-client:9.28
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.28
    profiles: [client]
  bitvise-client-9.31:
    image: rub-nds/bitvise-client:9.31
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.31
    profiles: [client]
  bitvise-client-9.33:
    image: rub-nds/bitvise-client:9.33
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.33
    profiles: [client]
  bitvise-client-9.34:
    image: rub-nds/bitvise-client:9.34
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.34
    profiles: [client]
  bitvise-client-9.35:
    image: rub-nds/bitvise-client:9.35
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.35
    profiles: [client]
  bitvise-client-9.37:
    image: rub-nds/bitvise-client:9.37
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.37
    profiles: [client]
  bitvise-client-9.38:
    image: rub-nds/bitvise-client:9.38
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.38
    profiles: [client]
  bitvise-client-9.39:
    image: rub-nds/bitvise-client:9.39
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.39
    profiles: [client]
  bitvise-client-9.41:
    image: rub-nds/bitvise-client:9.41
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.41
    profiles: [client]
  bitvise-client-9.42:
    image: rub-nds/bitvise-client:9.42
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.42
    profiles: [client]
  bitvise-client-9.43:
    image: rub-nds/bitvise-client:9.43
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: 9.43
    profiles: [client]
