# Builds an asyncssh 2.8.1 server patched to reuse the transient public key used in the RSA key-exchange
FROM python:3.9-slim-bullseye

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY simple_server.py ./
COPY vulnerability.py ./

ARG DEFAULT_USERNAME=sshattacker
ARG DEFAULT_PASSWORD=secret

ENV DEF_USER $DEFAULT_USERNAME
ENV DEF_PW $DEFAULT_PASSWORD

# Copy RSA server keys
COPY /server_keys/ssh_host_key* ./server_keys/
COPY /server_keys/rsa_1024* ./server_keys/

# Copy authorized pubkeys
COPY authorized_keys/ ./authorized_keys/

# Override kex_rsa.py file with patched version
WORKDIR /usr
COPY kex_rsa_static_key_patch.py ./local/lib/python3.9/site-packages/asyncssh/kex_rsa.py

# Switch back and run server
WORKDIR /usr/src/app
CMD [ "sh", "-c", "python ./simple_server.py $DEF_USER $DEF_PW" ]

EXPOSE 22
