#!/usr/bin/expect -f

set ip [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set password [lindex $argv 3]
set command [lindex $argv 4]

spawn plink -ssh "-P" "$port" "-l" "$user" "$ip"

set timeout 2
expect {
    "y/n" {
        send "y\r"
    }
}
expect {
	"assword:" {
         send "$password\r"
    }
}
expect {
	"Press Return to begin session" {
         send "\r"
    }
}
expect {
    ":" {
       send "$command\r"
    }
}

expect {
    ":" {
       send "\r"
    }
}


expect eof
