FROM debian-build:stretch-libssl1.0 AS libssh-builder
ARG VERSION
ARG USERNAME=sshattacker
ARG PASSWORD=bydahirsch
RUN git clone https://gitlab.com/libssh/libssh-mirror.git libssh \
  && cd libssh \
  && git checkout tags/libssh-${VERSION} \
  && sed -i s/myuser/${USERNAME}/g examples/ssh_server_fork.c \
  && sed -i s/mypassword/${PASSWORD}/g examples/ssh_server_fork.c
WORKDIR /src/libssh
RUN mkdir -p build \
  && cd build \
  # TODO: Determine which build type is favourable (can be set with -DMAKE_BUILD_TYPE)
  # Possible build type options are Debug Release MinSizeRel RelWithDebInfo
  && cmake -DCMAKE_INSTALL_PREFIX=/install .. \
  && make -j ${NUMCPUS:-8} \
  && make install

FROM debian:stretch AS libssh-server
ARG VERSION
RUN apt-get update && apt-get install -y \
  libssl1.0-dev \
  zlib1g-dev \
  && rm -rf /var/lib/apt/lists/*
COPY host_keys /install/host_keys/
COPY --from=libssh-builder /install /usr/
COPY --from=libssh-builder /src/libssh/build/examples /install/examples/
LABEL "ssh_implementation"="libssh"
LABEL "ssh_implementation_version"="${VERSION}"
LABEL "ssh_implementation_connectionRole"="server"
ENTRYPOINT [ "/install/examples/ssh_server_fork", \
  "-p", "22", \
  "-k", "/install/host_keys/ssh_host_dsa_key", \
  "-k", "/install/host_keys/ssh_host_rsa_key", \
  "-k", "/install/host_keys/ssh_host_ecdsa_key", \
  "0.0.0.0" ]
EXPOSE 22

