version: '3.2'
services:
  asyncssh-server-1.18.0:
    image: rub-nds/asyncssh-server:1.18.0
    build:
      context: .
      args:
        VERSION: 1.18.0
  asyncssh-server-1.17.1:
    image: rub-nds/asyncssh-server:1.17.1
    build:
      context: .
      args:
        VERSION: 1.17.1
  asyncssh-server-1.17.0:
    image: rub-nds/asyncssh-server:1.17.0
    build:
      context: .
      args:
        VERSION: 1.17.0
  asyncssh-server-1.16.1:
    image: rub-nds/asyncssh-server:1.16.1
    build:
      context: .
      args:
        VERSION: 1.16.1
  asyncssh-server-1.16.0:
    image: rub-nds/asyncssh-server:1.16.0
    build:
      context: .
      args:
        VERSION: 1.16.0
  asyncssh-server-1.15.1:
    image: rub-nds/asyncssh-server:1.15.1
    build:
      context: .
      args:
        VERSION: 1.15.1
  asyncssh-server-1.15.0:
    image: rub-nds/asyncssh-server:1.15.0
    build:
      context: .
      args:
        VERSION: 1.15.0
  asyncssh-server-1.14.0:
    image: rub-nds/asyncssh-server:1.14.0
    build:
      context: .
      args:
        VERSION: 1.14.0
  asyncssh-server-1.13.3:
    image: rub-nds/asyncssh-server:1.13.3
    build:
      context: .
      args:
        VERSION: 1.13.3
  asyncssh-server-1.13.2:
    image: rub-nds/asyncssh-server:1.13.02
    build:
      context: .
      args:
        VERSION: 1.13.2
  asyncssh-server-1.13.1:
    image: rub-nds/asyncssh-server:1.13.1
    build:
      context: .
      args:
        VERSION: 1.13.1
  asyncssh-server-1.13.0:
    image: rub-nds/asyncssh-server:1.13.0
    build:
      context: .
      args:
        VERSION: 1.13.0
  asyncssh-server-1.12.2:
    image: rub-nds/asyncssh-server:1.12.2
    build:
      context: .
      args:
        VERSION: 1.12.2
  asyncssh-server-1.12.1:
    image: rub-nds/asyncssh-server:1.12.1
    build:
      context: .
      args:
        VERSION: 1.12.1
  asyncssh-server-1.12.0:
    image: rub-nds/asyncssh-server:1.12.0
    build:
      context: .
      args:
        VERSION: 1.12.0
  asyncssh-server-1.11.1:
    image: rub-nds/asyncssh-server:1.11.1
    build:
      context: .
      args:
        VERSION: 1.11.1
  asyncssh-server-1.11.0:
    image: rub-nds/asyncssh-server:1.11.0
    build:
      context: .
      args:
        VERSION: 1.11.0
  asyncssh-server-1.10.1:
    image: rub-nds/asyncssh-server:1.10.1
    build:
      context: .
      args:
        VERSION: 1.10.1
  asyncssh-server-1.10.0:
    image: rub-nds/asyncssh-server:1.10.0
    build:
      context: .
      args:
        VERSION: 1.10.0
