# hadolint ignore=DL3049
FROM python:3.5 AS asyncssh-base

ARG VERSION
WORKDIR /app
RUN pip install --no-cache-dir asyncssh==$VERSION

# Server image asyncssh <2.0.0
FROM asyncssh-base AS asyncssh-server

ARG USERNAME=sshattacker
ARG PASSWORD=secret
ARG AUTHORIZED_KEYS_FILE=authorized_keys

# Copy server script and RSA server key
COPY files/simple_server_1.py files/ssh_host_key* ./

# Copy authorized pubkeys
COPY "files/${AUTHORIZED_KEYS_FILE}" "authorized_keys"

LABEL ssh.implementation.name="asyncssh" \
      ssh.implementation.version="${VERSION}" \
      ssh.implementation.type="server"
ENV USERNAME="${USERNAME}" PASSWORD="${PASSWORD}"
# Although the JSON notation for CMD is preferable, there is no straightforward
# way to pass env vars, so we just disable the warning here.
# hadolint ignore=DL3025
CMD python simple_server_1.py "${USERNAME}" --password "${PASSWORD}" --authorized-keys "authorized_keys"
EXPOSE 22
