ARG VERSION=latest

FROM debian:${VERSION}
ARG LIBSSL_VERSION
RUN apt-get update && apt-get install -y \
  build-essential \
  git \
  curl \
  wget \
  bash \
  libssl${LIBSSL_VERSION}-dev \
  zlib1g-dev \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /src