FROM debian-build:bullseye AS openssh-builder
ARG VERSION
RUN curl -s https://cloudflare.cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-${VERSION}.tar.gz | tar xzf -
WORKDIR /src/openssh-${VERSION}
RUN ./configure CFLAGS="-DDEBUG_KEX=1 -DDEBUG_KEXDH=1 -DDEBUG_KEXECDH=1" --prefix /install && \
  make -j ${NUMCPUS:-8} && \
  make install

FROM debian:bullseye AS openssh-server
ARG VERSION
RUN adduser --system --no-create-home sshd \
  && mkdir -p /var/empty \
  && (echo bydahirsch; echo bydahirsch) | adduser sshattacker --ingroup users
RUN apt-get update && apt-get install -y \
  libssl-dev \
  zlib1g-dev \
  && rm -rf /var/lib/apt/lists/*
COPY --from=openssh-builder /install /install
LABEL "ssh_implementation"="openssh"
LABEL "ssh_implementation_version"="${VERSION}"
LABEL "ssh_implementation_connectionRole"="server"
ENTRYPOINT ["/install/sbin/sshd", "-D", "-e"]
EXPOSE 22
