#!/usr/bin/expect -f

set ip [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set password [lindex $argv 3]
set command [lindex $argv 4]

spawn /install/bin/ssh "$ip" "-p" "$port" "-l" "$user"

set timeout 5
expect {
    "yes/no" {
        send "yes\r"
    }
}
expect {
	"password:" {
         send "$password\r"
    }
}
expect {
    "$ " {
       send "$command\r"
        }
}
expect {
    "$ " {
       send "$command\r"
        }
}
expect {
    "$ " {
       send "$command\r"
        }
}
expect {
    "$ " {
       send "exit\r"
        }
}


expect eof
