version: '3.2'
services:
  erlang-ssh-server-3.2:
    image: rub-nds/erlang-ssh-server:3.2
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: '17.5'
  erlang-ssh-server-3.2.4:
    image: rub-nds/erlang-ssh-server:3.2.4
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 17.5.6.9
  erlang-ssh-server-4.1:
    image: rub-nds/erlang-ssh-server:4.1
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: '18.1'
  erlang-ssh-server-4.1.2:
    image: rub-nds/erlang-ssh-server:4.1.2
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.1.4
  erlang-ssh-server-4.2:
    image: rub-nds/erlang-ssh-server:4.2
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.2.1
  erlang-ssh-server-4.2.1:
    image: rub-nds/erlang-ssh-server:4.2.1
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.2.3
  erlang-ssh-server-4.2.2:
    image: rub-nds/erlang-ssh-server:4.2.2
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.3.4
  erlang-ssh-server-4.2.2.1:
    image: rub-nds/erlang-ssh-server:4.2.2.1
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.3.4.1
  erlang-ssh-server-4.2.2.2:
    image: rub-nds/erlang-ssh-server:4.2.2.2
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.3.4.4
  erlang-ssh-server-4.2.2.3:
    image: rub-nds/erlang-ssh-server:4.2.2.3
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.3.4.5
  erlang-ssh-server-4.2.2.4:
    image: rub-nds/erlang-ssh-server:4.2.2.4
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.3.4.7
  erlang-ssh-server-4.2.2.5:
    image: rub-nds/erlang-ssh-server:4.2.2.5
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.3.4.8
  erlang-ssh-server-4.2.2.6:
    image: rub-nds/erlang-ssh-server:4.2.2.6
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 18.3.4.11
  erlang-ssh-server-4.3:
    image: rub-nds/erlang-ssh-server:4.3
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: '19.0'
  erlang-ssh-server-4.3.1:
    image: rub-nds/erlang-ssh-server:4.3.1
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 19.0.7
  erlang-ssh-server-4.3.2:
    image: rub-nds/erlang-ssh-server:4.3.2
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: '19.1'
  erlang-ssh-server-4.3.6:
    image: rub-nds/erlang-ssh-server:4.3.6
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 19.1.6
  erlang-ssh-server-4.4:
    image: rub-nds/erlang-ssh-server:4.4
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 19.2.3
  erlang-ssh-server-4.4.1:
    image: rub-nds/erlang-ssh-server:4.4.1
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: '19.3'
  erlang-ssh-server-4.4.2:
    image: rub-nds/erlang-ssh-server:4.4.2
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 19.3.6.4
  erlang-ssh-server-4.4.2.1:
    image: rub-nds/erlang-ssh-server:4.4.2.1
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 19.3.6.5
  erlang-ssh-server-4.4.2.2:
    image: rub-nds/erlang-ssh-server:4.4.2.2
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 19.3.6.7
  erlang-ssh-server-4.4.2.3:
    image: rub-nds/erlang-ssh-server:4.4.2.3
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 19.3.6.8
  erlang-ssh-server-4.4.2.4:
    image: rub-nds/erlang-ssh-server:4.4.2.4
    build:
      context: .
      dockerfile: Dockerfile.debian
      target: erlang-ssh-server
      args:
        VERSION: 19.3.6.13
  erlang-ssh-server-4.5:
    image: rub-nds/erlang-ssh-server:4.5
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.0.2
  erlang-ssh-server-4.5.1:
    image: rub-nds/erlang-ssh-server:4.5.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.0.5
  erlang-ssh-server-4.6:
    image: rub-nds/erlang-ssh-server:4.6
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: '20.1'
  erlang-ssh-server-4.6.1:
    image: rub-nds/erlang-ssh-server:4.6.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.1.5
  erlang-ssh-server-4.6.2:
    image: rub-nds/erlang-ssh-server:4.6.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.1.7
  erlang-ssh-server-4.6.3:
    image: rub-nds/erlang-ssh-server:4.6.3
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: '20.2'
  erlang-ssh-server-4.6.4:
    image: rub-nds/erlang-ssh-server:4.6.4
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.2.3
  erlang-ssh-server-4.6.5:
    image: rub-nds/erlang-ssh-server:4.6.5
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.2.4
  erlang-ssh-server-4.6.6:
    image: rub-nds/erlang-ssh-server:4.6.6
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.1
  erlang-ssh-server-4.6.7:
    image: rub-nds/erlang-ssh-server:4.6.7
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.3
  erlang-ssh-server-4.6.8:
    image: rub-nds/erlang-ssh-server:4.6.8
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.5
  erlang-ssh-server-4.6.9:
    image: rub-nds/erlang-ssh-server:4.6.9
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.8
  erlang-ssh-server-4.6.9.1:
    image: rub-nds/erlang-ssh-server:4.6.9.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.8.13
  erlang-ssh-server-4.6.9.2:
    image: rub-nds/erlang-ssh-server:4.6.9.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.8.15
  erlang-ssh-server-4.6.9.3:
    image: rub-nds/erlang-ssh-server:4.6.9.3
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.8.20
  erlang-ssh-server-4.6.9.4:
    image: rub-nds/erlang-ssh-server:4.6.9.4
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.8.23
  erlang-ssh-server-4.6.9.5:
    image: rub-nds/erlang-ssh-server:4.6.9.5
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.8.24
  erlang-ssh-server-4.6.9.6:
    image: rub-nds/erlang-ssh-server:4.6.9.6
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.8.25
  erlang-ssh-server-4.6.9.7:
    image: rub-nds/erlang-ssh-server:4.6.9.7
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 20.3.8.26
  erlang-ssh-server-4.7:
    image: rub-nds/erlang-ssh-server:4.7
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.0.9
  erlang-ssh-server-4.7.1:
    image: rub-nds/erlang-ssh-server:4.7.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.1.4
  erlang-ssh-server-4.7.2:
    image: rub-nds/erlang-ssh-server:4.7.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.2.1
  erlang-ssh-server-4.7.3:
    image: rub-nds/erlang-ssh-server:4.7.3
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.2.7
  erlang-ssh-server-4.7.4:
    image: rub-nds/erlang-ssh-server:4.7.4
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.3
  erlang-ssh-server-4.7.5:
    image: rub-nds/erlang-ssh-server:4.7.5
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.6
  erlang-ssh-server-4.7.6:
    image: rub-nds/erlang-ssh-server:4.7.6
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.8.6
  erlang-ssh-server-4.7.6.1:
    image: rub-nds/erlang-ssh-server:4.7.6.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.8.9
  erlang-ssh-server-4.7.6.2:
    image: rub-nds/erlang-ssh-server:4.7.6.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.8.11
  erlang-ssh-server-4.7.6.3:
    image: rub-nds/erlang-ssh-server:4.7.6.3
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.8.14
  erlang-ssh-server-4.7.6.4:
    image: rub-nds/erlang-ssh-server:4.7.6.4
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.8.17
  erlang-ssh-server-4.7.6.5:
    image: rub-nds/erlang-ssh-server:4.7.6.5
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.8.21
  erlang-ssh-server-4.7.6.6:
    image: rub-nds/erlang-ssh-server:4.7.6.6
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 21.3.8.24
  erlang-ssh-server-4.7.7:
    image: rub-nds/erlang-ssh-server:4.7.7
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.0.7
  erlang-ssh-server-4.8:
    image: rub-nds/erlang-ssh-server:4.8
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.1.8
  erlang-ssh-server-4.8.1:
    image: rub-nds/erlang-ssh-server:4.8.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.2.1
  erlang-ssh-server-4.8.2:
    image: rub-nds/erlang-ssh-server:4.8.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.2.8
  erlang-ssh-server-4.9:
    image: rub-nds/erlang-ssh-server:4.9
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.3.2
  erlang-ssh-server-4.9.1:
    image: rub-nds/erlang-ssh-server:4.9.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.3.4.8
  erlang-ssh-server-4.9.1.1:
    image: rub-nds/erlang-ssh-server:4.9.1.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.3.4.10
  erlang-ssh-server-4.9.1.2:
    image: rub-nds/erlang-ssh-server:4.9.1.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.3.4.16
  erlang-ssh-server-4.9.1.3:
    image: rub-nds/erlang-ssh-server:4.9.1.3
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.3.4.21
  erlang-ssh-server-4.9.1.4:
    image: rub-nds/erlang-ssh-server:4.9.1.4
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 22.3.4.26
  erlang-ssh-server-4.10:
    image: rub-nds/erlang-ssh-server:4.10
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.0.4
  erlang-ssh-server-4.10.1:
    image: rub-nds/erlang-ssh-server:4.10.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: '23.1'
  erlang-ssh-server-4.10.2:
    image: rub-nds/erlang-ssh-server:4.10.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.1.2
  erlang-ssh-server-4.10.3:
    image: rub-nds/erlang-ssh-server:4.10.3
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.1.3
  erlang-ssh-server-4.10.4:
    image: rub-nds/erlang-ssh-server:4.10.4
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.1.4
  erlang-ssh-server-4.10.5:
    image: rub-nds/erlang-ssh-server:4.10.5
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.1.5
  erlang-ssh-server-4.10.6:
    image: rub-nds/erlang-ssh-server:4.10.6
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.2.1
  erlang-ssh-server-4.10.7:
    image: rub-nds/erlang-ssh-server:4.10.7
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.2.5
  erlang-ssh-server-4.10.8:
    image: rub-nds/erlang-ssh-server:4.10.8
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.2.7
  erlang-ssh-server-4.11:
    image: rub-nds/erlang-ssh-server:4.11
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: '23.3'
  erlang-ssh-server-4.11.1:
    image: rub-nds/erlang-ssh-server:4.11.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.3.4
  erlang-ssh-server-4.11.1.1:
    image: rub-nds/erlang-ssh-server:4.11.1.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.3.4.1
  erlang-ssh-server-4.11.1.2:
    image: rub-nds/erlang-ssh-server:4.11.1.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.3.4.2
  erlang-ssh-server-4.11.1.3:
    image: rub-nds/erlang-ssh-server:4.11.1.3
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.3.4.7
  erlang-ssh-server-4.11.1.4:
    image: rub-nds/erlang-ssh-server:4.11.1.4
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.3.4.10
  erlang-ssh-server-4.11.1.5:
    image: rub-nds/erlang-ssh-server:4.11.1.5
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.3.4.14
  erlang-ssh-server-4.11.1.6:
    image: rub-nds/erlang-ssh-server:4.11.1.6
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 23.3.4.18
  erlang-ssh-server-4.12:
    image: rub-nds/erlang-ssh-server:4.12
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: '24.0'
  erlang-ssh-server-4.12.1:
    image: rub-nds/erlang-ssh-server:4.12.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.0.1
  erlang-ssh-server-4.12.2:
    image: rub-nds/erlang-ssh-server:4.12.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.0.2
  erlang-ssh-server-4.12.3:
    image: rub-nds/erlang-ssh-server:4.12.3
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.0.6
  erlang-ssh-server-4.12.4:
    image: rub-nds/erlang-ssh-server:4.12.4
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.1.6
  erlang-ssh-server-4.12.5:
    image: rub-nds/erlang-ssh-server:4.12.5
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.1.7
  erlang-ssh-server-4.13:
    image: rub-nds/erlang-ssh-server:4.13
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.2.1
  erlang-ssh-server-4.13.1:
    image: rub-nds/erlang-ssh-server:4.13.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.2.2
  erlang-ssh-server-4.13.2:
    image: rub-nds/erlang-ssh-server:4.13.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.3.4
  erlang-ssh-server-4.13.2.1:
    image: rub-nds/erlang-ssh-server:4.13.2.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.3.4.6
  erlang-ssh-server-4.13.2.2:
    image: rub-nds/erlang-ssh-server:4.13.2.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 24.3.4.9
  erlang-ssh-server-4.14:
    image: rub-nds/erlang-ssh-server:4.14
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: '25.0'
  erlang-ssh-server-4.14.1:
    image: rub-nds/erlang-ssh-server:4.14.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 25.0.4
  erlang-ssh-server-4.15:
    image: rub-nds/erlang-ssh-server:4.15
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 25.1.2
  erlang-ssh-server-4.15.1:
    image: rub-nds/erlang-ssh-server:4.15.1
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 25.2.2
  erlang-ssh-server-4.15.2:
    image: rub-nds/erlang-ssh-server:4.15.2
    build:
      context: .
      target: erlang-ssh-server
      args:
        VERSION: 25.2.3
