# Dockerfile for the SSH daemon included in Erlang/OTP
#
# Further information can be found at:
# - https://www.erlang.org/doc/apps/ssh/introduction.html
# - https://www.erlang.org/doc/man/ssh_app

ARG VERSION
# `erlang-ssh-base` is just an intermediate image and does not require labels,
# so we can disable that linter rule.
# hadolint ignore=DL3049
FROM erlang:${VERSION} AS erlang-ssh-base
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    && rm -rf /var/lib/apt/lists/*

ARG USERNAME=sshattacker
ARG PASSWORD=secret
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN useradd --create-home --groups users "${USERNAME}" && \
    echo "${USERNAME}:${PASSWORD}" | chpasswd

# Server image
FROM erlang-ssh-base AS erlang-ssh-server

ARG USERNAME
ARG DOTSSH=dotssh-server
COPY --chown="${USERNAME}:${USERNAME}" "${DOTSSH}" "/home/${USERNAME}/.ssh/"
RUN chmod -R g=,o= "/home/${USERNAME}/.ssh"

ARG VERSION
COPY hostkeys/* /etc/ssh/
LABEL ssh.implementation.name="erlang-ssh" \
      ssh.implementation.version="${VERSION}" \
      ssh.implementation.type="server"
ENTRYPOINT ["/usr/local/bin/erl", "-noshell", "-eval", "ssh:start()", "-eval", "ssh:daemon(22)"]
EXPOSE 22

# Client image
FROM erlang-ssh-base AS erlang-ssh-client

ARG USERNAME=sshattacker
COPY --chown="${USERNAME}:${USERNAME}" "../../keys" "/home/${USERNAME}/.ssh/"

COPY start_client.exp /usr/local/bin
WORKDIR "/usr/local/bin"

ARG VERSION
COPY hostkeys/* /etc/ssh/
LABEL ssh.implementation.name="erlang-ssh" \
      ssh.implementation.version="${VERSION}" \
      ssh.implementation.type="client"

ENTRYPOINT ["expect" , "start_client.exp"]
EXPOSE 22
