#!/usr/bin/expect -f

set ip [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set password [lindex $argv 3]
set command [lindex $argv 4]

spawn /usr/local/bin/erl

set timeout 5
expect {
    "1> " {
        send "ssh:start().\r"
    }
}

expect {
	"2> " {
        set erlang_string0 "{ok, S} = ssh:connect(\"$ip\", $port, \[{identity_file, \"/home/sshattacker/.ssh/id_rsa\"}\])"
        set erlang_string1 "{ok, S} = ssh:connect(\"$ip\", $port, \[{user, \"$user\"}\])"
        send "$erlang_string1.\r"
    }
}


expect eof
exit 0
