#!/usr/bin/expect -f

set ip [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set password [lindex $argv 3]
set command [lindex $argv 4]

spawn /usr/local/bin/erl


set timeout 5
expect {
    "1> " {
        send "ssh:start().\r"
    }
}

expect {
	"2> " {
        set erlang_string "{ok, S} = ssh:connect(\"127.0.0.1\", 22, \[{user, \"sshattacker\"}\])"
        send "$erlang_string.\r"
    }
    }


expect eof



exit 0
