# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Set up Python'
        uses: actions/setup-python@v3

      - name: 'Run pre-commit hooks'
        uses: pre-commit/action@v3.0.0

      - name: 'Generate patch file'
        if: failure()
        run: |
          git diff-index -p HEAD > "${PATCH_FILE}"
          [ -s "${PATCH_FILE}" ] && echo "UPLOAD_PATCH_FILE=${PATCH_FILE}" >> "${GITHUB_ENV}"
        env:
          PATCH_FILE: pre-commit.patch

      - name: 'Upload patch artifact'
        if: failure() && env.UPLOAD_PATCH_FILE != null
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.UPLOAD_PATCH_FILE }}
          path: ${{ env.UPLOAD_PATCH_FILE }}
